defaults.bluealsa.interface "hci0"
defaults.bluealsa.device "CE:9B:AB:F5:D4:BE"
defaults.bluealsa.profile "a2dp"

pcm.!default {
    type asym
    playback.pcm {
        type plug
        slave.pcm "bluealsa"
    }
    capture.pcm {
        type plug
        slave.pcm "hw:0,0"
    }
}
